spring:
  application:
    name: item-service
    
server:
  port: 8001

  cloud:
    config:
      override-none: true
      
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
    
  sleuth:
    sampler:
      probability: 0.1
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
